#include <stdlib.h>
#define TODO_OK 0
#define TABLERO_SIN_MEM -1
#define ARCHIVO_ERROR -1
#define TAM_BUFFER 512
#define PARAMETRO_FILA_UBICACION 0
#define PARAMETRO_COLUMNA_UBICACION 1
#define PARAMETRO_VIDAS_INICIO_UBICACION 2
#define PARAMETRO_CANT_FANTASMAS_UBICACION 3
#define PARAMETRO_CANT_PREMIOS_UBICACION 4
#define PARAMETRO_CANT_VIDAS_EXTRA_UBICACION 5
#define ES_NUMERO(X) ((X) >= '0' && (X) <= '9')
#define OBTENER_NUM_ALEATORIO(MIN,MAX,DST) \
    ((DST) = (rand() % ((MAX) - (MIN))) + (MIN))
#define LUGAR_VACIO ' '
#define CARACTER_FANTASMA 'F'
#define CARACTER_VIDA 'V'
#define CARACTER_ENTRADA 'E'
#define CARACTER_SALIDA 'S'
#define CARACTER_SALIDA 'S'
#define CARACTER_PREMIO 'P'
#define CARACTER_PARED '#'
#define MAX_CANT_PAREDES 10
#define POSICION_ESTA_DISPONIBLE(X,FI,COL) ((X[(FI)][(COL)]) == LUGAR_VACIO ? 1 : 0)
